### ISSUE TITLE
Supported slurm version

### ISSUE THREAD

**Issue by Al77056** [Azure/cyclecloud-slurm-workspace#141]
It looks like the currently supported slurm versions are defined in the configuration_slurm_version parameter in file slurm-workspace.txt, and I am trying to figure out how to get a different (later) version of slurm installed. I've tried to add "[Value="24.05.4"]" to the Config.Entries and change the input parameter slurmSettings.value.version to "24.05.4", and ended up with a scheduler vm with no slurm installed.

It looks like during the deployment, install.sh was uploaded as the osProfile.customData, which get executed after the installation. Inside install.sh, it's downloading the files inside folder "bicep/files-to-upload" from github, instead of actually uploading from my laptop.

Is my understanding above correct? If it is, what is the recommended way to customize the installation beyond those that can be changed through the deployment parameter file, such as using a different version of slurm?

**Comment by xpillons** [comment]
Your understanding are correct. Because there is a strict mapping between the version of CycleCloud, the autoscaler and Slurm, the versions supported are limited to the ones provided in the UI. Slurm version 24.05.4 will be added in the upcoming version of CycleCloud and Workspace for Slurm coming soon. 
The value of Workspace for Slurm is to provide you an environment ready to run, if you really need such level of customization and that particular Slurm version, then you may have to build your own CycleCloud environment, but you would have to install Slurm binaries in the image. I would really advice you to wait until we provide full end to end support.
Best,
Xavier
